interface GeographyOption {
  value: string;
  lookupName: string;
  label: string;
  hierarchy: string;
}

export const geographyConfig: GeographyOption[] = [
  {
    value: "318",
    lookupName: "World",
    hierarchy: "common",
    label: "World",
  },
  {
    value: "321",
    lookupName: "OECD & EU (R5)",
    hierarchy: "R5",
    label: "OECD & EU (R5)",
  },
  {
    value: "322",
    lookupName: "Reforming Economies (R5)",
    hierarchy: "R5",
    label: "Reforming Economies (R5)",
  },
  {
    value: "323",
    lookupName: "Asia (R5)",
    hierarchy: "R5",
    label: "Asia (R5)",
  },
  {
    value: "324",
    lookupName: "Middle East & Africa (R5)",
    hierarchy: "R5",
    label: "Middle East & Africa (R5)",
  },
  {
    value: "325",
    lookupName: "Latin America (R5)",
    hierarchy: "R5",
    label: "Latin America (R5)",
  },
  {
    value: "327",
    lookupName: "European Union (R9)",
    hierarchy: "R9",
    label: "European Union (R9)",
  },
  {
    value: "328",
    lookupName: "USA (R9)",
    hierarchy: "R9",
    label: "USA (R9)",
  },
  {
    value: "329",
    lookupName: "Other OECD (R9)",
    hierarchy: "R9",
    label: "Other OECD (R9)",
  },
  {
    value: "330",
    lookupName: "China (R9)",
    hierarchy: "R9",
    label: "China (R9)",
  },
  {
    value: "331",
    lookupName: "India (R9)",
    hierarchy: "R9",
    label: "India (R9)",
  },
  {
    value: "332",
    lookupName: "Other Asia (R9)",
    hierarchy: "R9",
    label: "Other Asia (R9)",
  },
  {
    value: "333",
    lookupName: "Reforming Economies (R9)",
    hierarchy: "R9",
    label: "Reforming Economies (R9)",
  },
  {
    value: "334",
    lookupName: "Middle East & Africa (R9)",
    hierarchy: "R9",
    label: "Middle East & Africa (R9)",
  },
  {
    value: "335",
    lookupName: "Latin America (R9)",
    hierarchy: "R9",
    label: "Latin America (R9)",
  },
  {
    value: "337",
    lookupName: "Africa (R10)",
    hierarchy: "R10",
    label: "Africa (R10)",
  },
  {
    value: "338",
    lookupName: "China+ (R10)",
    hierarchy: "R10",
    label: "China+ (R10)",
  },
  {
    value: "339",
    lookupName: "Europe (R10)",
    hierarchy: "R10",
    label: "Europe (R10)",
  },
  {
    value: "340",
    lookupName: "India+ (R10)",
    hierarchy: "R10",
    label: "India+ (R10)",
  },
  {
    value: "341",
    lookupName: "Latin America (R10)",
    hierarchy: "R10",
    label: "Latin America (R10)",
  },
  {
    value: "342",
    lookupName: "Middle East (R10)",
    hierarchy: "R10",
    label: "Middle East (R10)",
  },
  {
    value: "343",
    lookupName: "North America (R10)",
    hierarchy: "R10",
    label: "North America (R10)",
  },
  {
    value: "344",
    lookupName: "Pacific OECD (R10)",
    hierarchy: "R10",
    label: "Pacific OECD (R10)",
  },
  {
    value: "345",
    lookupName: "Reforming Economies (R10)",
    hierarchy: "R10",
    label: "Reforming Economies (R10)",
  },
  {
    value: "346",
    lookupName: "Rest of Asia (R10)",
    hierarchy: "R10",
    label: "Rest of Asia (R10)",
  },
  {
    value: "347",
    lookupName: "Other (R10)",
    hierarchy: "R10",
    label: "Other (R10)",
  },
  {
    value: "350",
    lookupName: "Brazil",
    hierarchy: "G20 Members",
    label: "Brazil (G20)",
  },
  {
    value: "351",
    lookupName: "Canada",
    hierarchy: "G20 Members",
    label: "Canada (G20)",
  },
  {
    value: "352",
    lookupName: "China",
    hierarchy: "G20 Members",
    label: "China (G20)",
  },
  {
    value: "355",
    lookupName: "India",
    hierarchy: "G20 Members",
    label: "India (G20)",
  },
  {
    value: "356",
    lookupName: "Indonesia",
    hierarchy: "G20 Members",
    label: "Indonesia (G20)",
  },
  {
    value: "358",
    lookupName: "Japan",
    hierarchy: "G20 Members",
    label: "Japan (G20)",
  },
  {
    value: "359",
    lookupName: "Mexico",
    hierarchy: "G20 Members",
    label: "Mexico (G20)",
  },
  {
    value: "360",
    lookupName: "Russian Federation",
    hierarchy: "G20 Members",
    label: "Russian Federation (G20)",
  },
  {
    value: "362",
    lookupName: "South Africa",
    hierarchy: "G20 Members",
    label: "South Africa (G20)",
  },
  {
    value: "364",
    lookupName: "Turkey",
    hierarchy: "G20 Members",
    label: "Turkey (G20)",
  },
  {
    value: "366",
    lookupName: "United States",
    hierarchy: "G20 Members",
    label: "United States (G20)",
  },
  {
    value: "369",
    lookupName: "European Union and United Kingdom",
    hierarchy: "G20 Members",
    label: "European Union and United Kingdom (G20)",
  },
  {
    value: "429",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|China",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "China",
  },
  {
    value: "430",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Eastern Europe",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Eastern Europe",
  },
  {
    value: "431",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Former Soviet Union",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Former Soviet Union",
  },
  {
    value: "432",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Latin America and the Caribbean",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Latin America and the Caribbean (MSG)",
  },
  {
    value: "433",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Middle East and North Africa",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Middle East and North Africa (MSG)",
  },
  {
    value: "434",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|North America",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "North America",
  },
  {
    value: "435",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Other Pacific Asia",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Other Pacific Asia",
  },
  {
    value: "436",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Pacific OECD",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Pacific OECD",
  },
  {
    value: "437",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Rest of Centrally Planned Asia",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Rest of Centrally Planned Asia",
  },
  {
    value: "438",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|South Asia",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "South Asia",
  },
  {
    value: "439",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Sub-Saharan Africa",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Sub-Saharan Africa (MSG)",
  },
  {
    value: "440",
    lookupName: "MESSAGEix-GLOBIOM 1.1-R12|Western Europe",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
    label: "Western Europe",
  },
  {
    value: "529",
    lookupName: "IMAGE 3.3|Brazil",
    hierarchy: "IMAGE 3.3",
    label: "Brazil (IMG)",
  },
  {
    value: "530",
    lookupName: "IMAGE 3.3|Canada",
    hierarchy: "IMAGE 3.3",
    label: "Canada (IMG)",
  },
  {
    value: "531",
    lookupName: "IMAGE 3.3|Central America",
    hierarchy: "IMAGE 3.3",
    label: "Central America (IMG)",
  },
  {
    value: "532",
    lookupName: "IMAGE 3.3|Central Asia",
    hierarchy: "IMAGE 3.3",
    label: "Central Asia (IMG)",
  },
  {
    value: "533",
    lookupName: "IMAGE 3.3|Central Europe",
    hierarchy: "IMAGE 3.3",
    label: "Central Europe (IMG)",
  },
  {
    value: "534",
    lookupName: "IMAGE 3.3|China Region",
    hierarchy: "IMAGE 3.3",
    label: "China Region (IMG)",
  },
  {
    value: "535",
    lookupName: "IMAGE 3.3|Eastern Africa",
    hierarchy: "IMAGE 3.3",
    label: "Eastern Africa (IMG)",
  },
  {
    value: "536",
    lookupName: "IMAGE 3.3|India",
    hierarchy: "IMAGE 3.3",
    label: "India (IMG)",
  },
  {
    value: "537",
    lookupName: "IMAGE 3.3|Indonesia Region",
    hierarchy: "IMAGE 3.3",
    label: "Indonesia Region (IMG)",
  },
  {
    value: "538",
    lookupName: "IMAGE 3.3|Japan",
    hierarchy: "IMAGE 3.3",
    label: "Japan (IMG)",
  },
  {
    value: "539",
    lookupName: "IMAGE 3.3|Korea Region",
    hierarchy: "IMAGE 3.3",
    label: "Korea Region (IMG)",
  },
  {
    value: "540",
    lookupName: "IMAGE 3.3|Mexico",
    hierarchy: "IMAGE 3.3",
    label: "Mexico (IMG)",
  },
  {
    value: "541",
    lookupName: "IMAGE 3.3|Middle East",
    hierarchy: "IMAGE 3.3",
    label: "Middle East (IMG)",
  },
  {
    value: "542",
    lookupName: "IMAGE 3.3|Northern Africa",
    hierarchy: "IMAGE 3.3",
    label: "Northern Africa (IMG)",
  },
  {
    value: "543",
    lookupName: "IMAGE 3.3|Oceania",
    hierarchy: "IMAGE 3.3",
    label: "Oceania (IMG)",
  },
  {
    value: "544",
    lookupName: "IMAGE 3.3|Rest of South America",
    hierarchy: "IMAGE 3.3",
    label: "Rest of South America (IMG)",
  },
  {
    value: "545",
    lookupName: "IMAGE 3.3|Rest of South Asia",
    hierarchy: "IMAGE 3.3",
    label: "Rest of South Asia (IMG)",
  },
  {
    value: "546",
    lookupName: "IMAGE 3.3|Rest of Southern Africa",
    hierarchy: "IMAGE 3.3",
    label: "Rest of Southern Africa (IMG)",
  },
  {
    value: "547",
    lookupName: "IMAGE 3.3|Russia Region",
    hierarchy: "IMAGE 3.3",
    label: "Russia Region (IMG)",
  },
  {
    value: "548",
    lookupName: "IMAGE 3.3|South Africa",
    hierarchy: "IMAGE 3.3",
    label: "South Africa (IMG)",
  },
  {
    value: "549",
    lookupName: "IMAGE 3.3|Southeastern Asia",
    hierarchy: "IMAGE 3.3",
    label: "Southeastern Asia (IMG)",
  },
  {
    value: "550",
    lookupName: "IMAGE 3.3|Turkey",
    hierarchy: "IMAGE 3.3",
    label: "Turkey (IMG)",
  },
  {
    value: "551",
    lookupName: "IMAGE 3.3|Ukraine Region",
    hierarchy: "IMAGE 3.3",
    label: "Ukraine Region (IMG)",
  },
  {
    value: "552",
    lookupName: "IMAGE 3.3|United States",
    hierarchy: "IMAGE 3.3",
    label: "United States (IMG)",
  },
  {
    value: "553",
    lookupName: "IMAGE 3.3|Western Africa",
    hierarchy: "IMAGE 3.3",
    label: "Western Africa (IMG)",
  },
  {
    value: "554",
    lookupName: "IMAGE 3.3|Western Europe",
    hierarchy: "IMAGE 3.3",
    label: "Western Europe (IMG)",
  },
  {
    value: "567",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Canada, Australia, New Zealand",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Canada, Australia, New Zealand",
  },
  {
    value: "568",
    lookupName: "REMIND-MAgPIE 3.2-4.6|China and Taiwan",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "China and Taiwan",
  },
  {
    value: "569",
    lookupName: "REMIND-MAgPIE 3.2-4.6|EU 28",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "EU 28",
  },
  {
    value: "570",
    lookupName: "REMIND-MAgPIE 3.2-4.6|India",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "India",
  },
  {
    value: "571",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Japan",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Japan",
  },
  {
    value: "572",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Latin America and the Caribbean",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Latin America and the Caribbean (RMD)",
  },
  {
    value: "573",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Middle East and North Africa",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Middle East and North Africa (RMD)",
  },
  {
    value: "574",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Non-EU28 Europe",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Non-EU28 Europe",
  },
  {
    value: "575",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Other Asia",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Other Asia",
  },
  {
    value: "576",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Russia and Reforming Economies",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Russia and Reforming Economies",
  },
  {
    value: "577",
    lookupName: "REMIND-MAgPIE 3.2-4.6|Sub-Saharan Africa",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "Sub-Saharan Africa (RMD)",
  },
  {
    value: "578",
    lookupName: "REMIND-MAgPIE 3.2-4.6|United States of America",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
    label: "United States of America",
  },
];

export const GEOGRAPHY_VALUES = geographyConfig.map((option) => option.value);
