interface GeographyOption {
  value: string;
  label: string;
  hierarchy: string;
}

export const geographyOptions: GeographyOption[] = [
  { value: "318", label: "World", hierarchy: "common" },
  { value: "321", label: "OECD & EU (R5)", hierarchy: "R5" },
  { value: "322", label: "Reforming Economies (R5)", hierarchy: "R5" },
  { value: "323", label: "Asia (R5)", hierarchy: "R5" },
  { value: "324", label: "Middle East & Africa (R5)", hierarchy: "R5" },
  { value: "325", label: "Latin America (R5)", hierarchy: "R5" },
  { value: "327", label: "European Union (R9)", hierarchy: "R9" },
  { value: "328", label: "USA (R9)", hierarchy: "R9" },
  { value: "329", label: "Other OECD (R9)", hierarchy: "R9" },
  { value: "330", label: "China (R9)", hierarchy: "R9" },
  { value: "331", label: "India (R9)", hierarchy: "R9" },
  { value: "332", label: "Other Asia (R9)", hierarchy: "R9" },
  { value: "333", label: "Reforming Economies (R9)", hierarchy: "R9" },
  { value: "334", label: "Middle East & Africa (R9)", hierarchy: "R9" },
  { value: "335", label: "Latin America (R9)", hierarchy: "R9" },
  { value: "337", label: "Africa (R10)", hierarchy: "R10" },
  { value: "338", label: "China+ (R10)", hierarchy: "R10" },
  { value: "339", label: "Europe (R10)", hierarchy: "R10" },
  { value: "340", label: "India+ (R10)", hierarchy: "R10" },
  { value: "341", label: "Latin America (R10)", hierarchy: "R10" },
  { value: "342", label: "Middle East (R10)", hierarchy: "R10" },
  { value: "343", label: "North America (R10)", hierarchy: "R10" },
  { value: "344", label: "Pacific OECD (R10)", hierarchy: "R10" },
  { value: "345", label: "Reforming Economies (R10)", hierarchy: "R10" },
  { value: "346", label: "Rest of Asia (R10)", hierarchy: "R10" },
  { value: "347", label: "Other (R10)", hierarchy: "R10" },
  { value: "350", label: "Brazil", hierarchy: "G20 Members" },
  { value: "351", label: "Canada", hierarchy: "G20 Members" },
  { value: "352", label: "China", hierarchy: "G20 Members" },
  { value: "355", label: "India", hierarchy: "G20 Members" },
  { value: "356", label: "Indonesia", hierarchy: "G20 Members" },
  { value: "358", label: "Japan", hierarchy: "G20 Members" },
  { value: "359", label: "Mexico", hierarchy: "G20 Members" },
  { value: "360", label: "Russian Federation", hierarchy: "G20 Members" },
  { value: "362", label: "South Africa", hierarchy: "G20 Members" },
  { value: "364", label: "Turkey", hierarchy: "G20 Members" },
  { value: "366", label: "United States", hierarchy: "G20 Members" },
  { value: "369", label: "European Union and United Kingdom", hierarchy: "G20 Members" },
  {
    value: "429",
    label: "MESSAGEix-GLOBIOM 1.1-R12|China",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "430",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Eastern Europe",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "431",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Former Soviet Union",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "432",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Latin America and the Caribbean",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "433",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Middle East and North Africa",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "434",
    label: "MESSAGEix-GLOBIOM 1.1-R12|North America",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "435",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Other Pacific Asia",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "436",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Pacific OECD",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "437",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Rest of Centrally Planned Asia",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "438",
    label: "MESSAGEix-GLOBIOM 1.1-R12|South Asia",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "439",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Sub-Saharan Africa",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  {
    value: "440",
    label: "MESSAGEix-GLOBIOM 1.1-R12|Western Europe",
    hierarchy: "MESSAGEix-GLOBIOM 1.1-R12",
  },
  { value: "529", label: "IMAGE 3.3|Brazil", hierarchy: "IMAGE 3.3" },
  { value: "530", label: "IMAGE 3.3|Canada", hierarchy: "IMAGE 3.3" },
  { value: "531", label: "IMAGE 3.3|Central America", hierarchy: "IMAGE 3.3" },
  { value: "532", label: "IMAGE 3.3|Central Asia", hierarchy: "IMAGE 3.3" },
  { value: "533", label: "IMAGE 3.3|Central Europe", hierarchy: "IMAGE 3.3" },
  { value: "534", label: "IMAGE 3.3|China Region", hierarchy: "IMAGE 3.3" },
  { value: "535", label: "IMAGE 3.3|Eastern Africa", hierarchy: "IMAGE 3.3" },
  { value: "536", label: "IMAGE 3.3|India", hierarchy: "IMAGE 3.3" },
  { value: "537", label: "IMAGE 3.3|Indonesia Region", hierarchy: "IMAGE 3.3" },
  { value: "538", label: "IMAGE 3.3|Japan", hierarchy: "IMAGE 3.3" },
  { value: "539", label: "IMAGE 3.3|Korea Region", hierarchy: "IMAGE 3.3" },
  { value: "540", label: "IMAGE 3.3|Mexico", hierarchy: "IMAGE 3.3" },
  { value: "541", label: "IMAGE 3.3|Middle East", hierarchy: "IMAGE 3.3" },
  { value: "542", label: "IMAGE 3.3|Northern Africa", hierarchy: "IMAGE 3.3" },
  { value: "543", label: "IMAGE 3.3|Oceania", hierarchy: "IMAGE 3.3" },
  { value: "544", label: "IMAGE 3.3|Rest of South America", hierarchy: "IMAGE 3.3" },
  { value: "545", label: "IMAGE 3.3|Rest of South Asia", hierarchy: "IMAGE 3.3" },
  { value: "546", label: "IMAGE 3.3|Rest of Southern Africa", hierarchy: "IMAGE 3.3" },
  { value: "547", label: "IMAGE 3.3|Russia Region", hierarchy: "IMAGE 3.3" },
  { value: "548", label: "IMAGE 3.3|South Africa", hierarchy: "IMAGE 3.3" },
  { value: "549", label: "IMAGE 3.3|Southeastern Asia", hierarchy: "IMAGE 3.3" },
  { value: "550", label: "IMAGE 3.3|Turkey", hierarchy: "IMAGE 3.3" },
  { value: "551", label: "IMAGE 3.3|Ukraine Region", hierarchy: "IMAGE 3.3" },
  { value: "552", label: "IMAGE 3.3|United States", hierarchy: "IMAGE 3.3" },
  { value: "553", label: "IMAGE 3.3|Western Africa", hierarchy: "IMAGE 3.3" },
  { value: "554", label: "IMAGE 3.3|Western Europe", hierarchy: "IMAGE 3.3" },
  {
    value: "567",
    label: "REMIND-MAgPIE 3.2-4.6|Canada, Australia, New Zealand",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  {
    value: "568",
    label: "REMIND-MAgPIE 3.2-4.6|China and Taiwan",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  { value: "569", label: "REMIND-MAgPIE 3.2-4.6|EU 28", hierarchy: "REMIND-MAgPIE 3.2-4.6" },
  { value: "570", label: "REMIND-MAgPIE 3.2-4.6|India", hierarchy: "REMIND-MAgPIE 3.2-4.6" },
  { value: "571", label: "REMIND-MAgPIE 3.2-4.6|Japan", hierarchy: "REMIND-MAgPIE 3.2-4.6" },
  {
    value: "572",
    label: "REMIND-MAgPIE 3.2-4.6|Latin America and the Caribbean",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  {
    value: "573",
    label: "REMIND-MAgPIE 3.2-4.6|Middle East and North Africa",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  {
    value: "574",
    label: "REMIND-MAgPIE 3.2-4.6|Non-EU28 Europe",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  { value: "575", label: "REMIND-MAgPIE 3.2-4.6|Other Asia", hierarchy: "REMIND-MAgPIE 3.2-4.6" },
  {
    value: "576",
    label: "REMIND-MAgPIE 3.2-4.6|Russia and Reforming Economies",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  {
    value: "577",
    label: "REMIND-MAgPIE 3.2-4.6|Sub-Saharan Africa",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
  {
    value: "578",
    label: "REMIND-MAgPIE 3.2-4.6|United States of America",
    hierarchy: "REMIND-MAgPIE 3.2-4.6",
  },
];

export const GEOGRAPHY_VALUES = geographyOptions.map((option) => option.value);
